{% set name = "sphinxdft" %}
{% set version = "3.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
#  url: https://github.com/eisenforschung/sphinx/archive/{{ version }}.tar.gz
  url: https://sxrepo.mpie.de/attachments/download/70/sphinx-3.0.7.tar.xz
  sha256: 8778b99a0d0d49864b3c80553fa37653ad3d4943f801aa8534e96296c95d9f6a

build:
  number: 3
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - libtool
    - make
  host:
    - libnetcdf
    - mkl
    - mkl-include
    - pcre2
  run:
    - {{ pin_compatible("mkl") }} 
    - sphinxdft-data

test:
  files:
    - Al_GGA.atomicdata
    - input.sx
  commands:
    - sphinx  # test calculation
    - sphinx --help
    - sx2aims --help
    - sxb2bspectrum --help
    - sxdielec --help
    - sxfastbs --help
    - sxmies --help
    - sxrho2dx --help
    - sxstructparam --help
    - sxthermo --help
    - sx2dx --help
    - sxbader --help
    - sxdynmat --help
    - sxfindk --help
    - sxmulliken --help
    - sxrhodiff --help
    - sxstructpatch --help
    - sxuniqdispl --help
    - sx2gwst --help
    - sxbandaodecomp --help
    - sxeffmass --help
    - sxforces --help
    - sxmurn --help
    - sxrhograd --help
    - sxstructprint --help
    - sxvibrations --help
    - sx2pdb --help
    - sxbandinfo --help
    - sxelnes --help
    - sxgetfermi --help
    - sxpartialrho --help
    - sxrhorep --help
    - sxstructrel --help
    - sxwannier --help
    - sx2poscar --help
    - sxblocksizes --help
    - sxeprhyper --help
    # - sxgetskfiles --help  # ERROR: SPHInX compiled without TB support
    - sxpdos --help
    - sxrhosplit --help
    - sxstructrep --help
    - sxwannierham --help
    - sx2xsf --help
    - sxcalcpot --help
    - sxepscontrib --help
    - sxharmpottst --help
    - sxpespectrum --help
    - sxrictst --help
    - sxstructrot --help
    # - sxwaveh5tosxb --help  # Tool is only working with HDF5 support!
    - sx2xyz --help
    - sxcalcquamoloverlap --help
    - sxepscontribpaw --help
    - sxinterpol --help
    - sxphonon --help
    - sxsawtooth --help
    - sxstructshift --help
    - sxwavescmp --help
    - sxaojoin --help
    - sxcheckinput --help
    - sxepsprint --help
    - sxkpprint --help
    - sxposmatel --help
    - sxslab --help
    - sxstructsort --help
    - sxwavesjoin --help
    - sxaomat --help
    - sxdefectalign --help
    - sxepsslope --help
    - sxlocalenergy --help
    - sxprintocc --help
    - sxstructcom --help
    - sxstructsym --help
    - sxwavesym --help
    - sxaomattb --help
    - sxdefectalign2d --help
    - sxestimate --help
    - sxmeshline --help
    - sxquamol --help
    - sxstructdiff --help
    - sxsym --help
    - sxwavetransfer --help
    - sxatomicspin --help
    - sxdefectconc --help
    - sxextopt --help
    - sxmeshtrace --help
    - sxquamolredsubspace --help
    - sxstructjoin --help
    - sxtdos --help
    - sxzdos --help

about:
  home: https://sxrepo.mpie.de
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: S/PHI/nX is a C++ library for materials simulation, mostly electronic-structure theory

  description: |
    S/PHI/nX is a C++ library for materials simulation, mostly 
    electronic-structure theory. It also is a program (sphinx) to perform 
    such simulations using density-functional theory, and k.p theory.
  doc_url: https://sxrepo.mpie.de/attachments/download/41/sphinx-manual-2.6.pdf
  dev_url: https://sxrepo.mpie.de

extra:
  recipe-maintainers:
    - jan-janssen
    - freyso
