travis:
  secure:
    BINSTAR_TOKEN: YcsdEqEBpVggj9AgrEnULPqgaa5VtdW/UoMS6nMOJW1DOMlF+7p/APhZsZcTsEVp3m3ukTuOqS0arTo7sv3OQ7sXyOROY0OGxanVMN732v6aQp2ZNrnLmkGad/9SCcuWHyhhOzb/aKvj750n8iBHqJKB687+OCCdwJquhL0cO2X+j3ayy7vbRvQ3xX3verUrQOyp9C4wXFapk3rdbJf1dj6SIpiriiwJlcpx+eZwYaTsoaxIh/0nXE38rGht7kJ3Icn/UyWeIQ5NyUP+DGcVkOGmwxggL8YRxM5HXZECc1Mr69O3mo8BGE3L3AReKg26fgffrCfp+Sgao57K9e5oQu7z5cS1rj7x6hd+N7nr7bhtHhoUQY/x4Ej562A3Qqmi+Divp9M7/YBe694wk80TTnR82c30wovCsp37pLTdKKoV0EGm2enJj8HVWVf7OfL7/kxhtXTMms/khxgcdsZIJkdZOes6cKYS5hdD3XER6kzSOp3+aAGXjDAXsqLwiGtRHL3fS2druzj82aRnwXL5wLW6X7v6HgqoeP0/hQX1I2BnPSIA4+mF+nZ8kP4KkiTR+5+hCjP4Y4a9n+B5fnORVXLzO3soqquZni1PzhVJim7stzTE/80WLLkA5VpHJvrG+gTaiKl+ornbKNInW6AH2I4TeffdFRbTKGW57SH/HYI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
